from django.urls import path
from .views import (
    Ish,
    Home,
    Other,
    Table,
    Maktab,
    Kollej,
    Schools,
    OTM_Enter,
    Districts,
    OTM_Finish,
    Akmal,
    Bekmatov,
    Bekzod, 
    Dilshod, 
    Jasur,
    Akmal_,
    Bekmatov_,
    Bekzod_, 
    Dilshod_, 
    Jasur_,
    MaktabAdd,
    load_mahalla,
    load_maktab,
    DataAdd,
    KollejAdd,
    load_kollej,
    UniversitetAdd,
    AllDistricts,
)
urlpatterns = [
    path("", Home, name="H"),
    path("ish/", Ish, name="I"),
    path("other/", Other, name="O"),
    path("maktab/", Maktab, name="M"),
    path("kollej/", Kollej, name="K"),
    path("enter/", OTM_Enter, name="E"),
    path("finish/", OTM_Finish, name="F"),
    path("akmal/", Akmal, name="ACV"),
    path("bekmatov/", Bekmatov, name="BCV"),
    path("bekzod/", Bekzod, name="BeCV"),
    path("dilshod/", Dilshod, name="DCV"),
    path("jasur/", Jasur, name="JCV"),
    path("akmal_/", Akmal_, name="ACV_"),
    path("bekmatov_/", Bekmatov_, name="BCV_"),
    path("bekzod_/", Bekzod_, name="BeCV_"),
    path("dilshod_/", Dilshod_, name="DCV_"),
    path("jasur_/", Jasur_, name="JCV_"),
    path("tuman/<pk>/", Districts, name="D"),
    path("tumanlar/all/", AllDistricts, name="AD"),
    path("tumanlar/maktablar/<pk>/", Schools, name="S"),
    path("table/", Table, name="T"),
    path("data/new/add/", DataAdd, name="DA"),
    path("bitiruvchi/maktab/new/add/", MaktabAdd, name="MBA"),
    path("bitiruvchi/kollej/new/add/", KollejAdd, name="KBA"),
    path("bitiruvchi/universitet/new/add/", UniversitetAdd, name="UBA"),
    path("ajax/load/mahalla/list", load_mahalla, name="ALM"),
    path("ajax/load/maktab/list", load_maktab, name="ALMa"),
    path("ajax/load/kollej/list", load_kollej, name="ALK"),
]