# Generated by Django 4.0.6 on 2022-08-04 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AutoTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Nomi')),
                ('add_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Bitiruvchi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=300, verbose_name='F.I.Sh')),
                ('t_sana', models.DateField(verbose_name="Tug'ulgan sana")),
                ('phone', models.CharField(max_length=9, verbose_name='(+998) ')),
                ('email', models.EmailField(max_length=300, null=True, verbose_name='E-Pochta')),
                ('guvohnoma', models.CharField(choices=[('Bor', 'Bor'), ('Yoq', 'Yoq')], default='Yoq', max_length=300, verbose_name='Haydovchilik Guvohnomasi')),
                ('idea', models.CharField(choices=[('Bor', 'Bor'), ('Yoq', 'Yoq')], default='Yoq', max_length=300, verbose_name="Biznes g'oya")),
            ],
        ),
        migrations.CreateModel(
            name='ChetTili',
            fields=[
                ('autotime_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.autotime')),
            ],
            bases=('main.autotime',),
        ),
        migrations.CreateModel(
            name='Imkonyat',
            fields=[
                ('autotime_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.autotime')),
            ],
            bases=('main.autotime',),
        ),
        migrations.CreateModel(
            name='Kollej',
            fields=[
                ('autotime_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.autotime')),
            ],
            bases=('main.autotime',),
        ),
        migrations.CreateModel(
            name='Maktab',
            fields=[
                ('autotime_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.autotime')),
            ],
            bases=('main.autotime',),
        ),
        migrations.CreateModel(
            name='Qiziqish',
            fields=[
                ('autotime_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.autotime')),
            ],
            bases=('main.autotime',),
        ),
        migrations.CreateModel(
            name='TumanVaShahar',
            fields=[
                ('autotime_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.autotime')),
                ('status', models.CharField(choices=[('tuman', 'tuman'), ('shahar', 'shahar')], default='shaxar', max_length=300)),
            ],
            bases=('main.autotime',),
        ),
        migrations.CreateModel(
            name='Universitet',
            fields=[
                ('autotime_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.autotime')),
                ('tuman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.tumanvashahar', verbose_name='Qaysi tuman')),
            ],
            bases=('main.autotime',),
        ),
        migrations.CreateModel(
            name='UniversitetBitiruvchisi',
            fields=[
                ('bitiruvchi_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.bitiruvchi')),
                ('universitet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.universitet', verbose_name='Bitirayotgan OTM')),
            ],
            bases=('main.bitiruvchi',),
        ),
        migrations.CreateModel(
            name='MaktabBitiruvchisi',
            fields=[
                ('bitiruvchi_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.bitiruvchi')),
                ('maktab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.maktab', verbose_name='Bitirayotgan maktab')),
            ],
            bases=('main.bitiruvchi',),
        ),
        migrations.AddField(
            model_name='maktab',
            name='tuman',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.tumanvashahar', verbose_name='Qaysi tuman'),
        ),
        migrations.CreateModel(
            name='Mahalla',
            fields=[
                ('autotime_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.autotime')),
                ('tuman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.tumanvashahar', verbose_name='Qaysi tuman')),
            ],
            bases=('main.autotime',),
        ),
        migrations.CreateModel(
            name='KollejBitiruvchisi',
            fields=[
                ('bitiruvchi_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.bitiruvchi')),
                ('kollej', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.kollej', verbose_name='Bitirayotgan Kollej')),
            ],
            bases=('main.bitiruvchi',),
        ),
        migrations.AddField(
            model_name='kollej',
            name='tuman',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.tumanvashahar', verbose_name='Qaysi tuman'),
        ),
        migrations.AddField(
            model_name='bitiruvchi',
            name='chettili',
            field=models.ManyToManyField(related_name='f_lang', to='main.chettili'),
        ),
        migrations.AddField(
            model_name='bitiruvchi',
            name='imkonyat',
            field=models.ManyToManyField(related_name='abilty', to='main.imkonyat', verbose_name='Qoshimcha bilimi'),
        ),
        migrations.AddField(
            model_name='bitiruvchi',
            name='mahalla',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.mahalla', verbose_name='Mahalla Nomi'),
        ),
        migrations.AddField(
            model_name='bitiruvchi',
            name='qiziqish',
            field=models.ManyToManyField(related_name='interest', to='main.qiziqish'),
        ),
        migrations.AddField(
            model_name='bitiruvchi',
            name='tuman',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.tumanvashahar', verbose_name='Yashaydigan tuman(shahar)'),
        ),
    ]
