# Generated by Django 4.0.6 on 2022-08-04 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='maktab',
            name='status',
            field=models.CharField(default='maktab', max_length=300, null=True),
        ),
    ]
