# Generated by Django 4.0.6 on 2022-08-16 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_bitiruvchi_add_time_alter_bitiruvchi_idea'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bitiruvchi',
            name='email',
            field=models.EmailField(blank=True, max_length=300, null=True, verbose_name='E-Pochta'),
        ),
        migrations.AlterField(
            model_name='bitiruvchi',
            name='t_sana',
            field=models.DateField(blank=True, null=True, verbose_name="Tug'ulgan sana"),
        ),
    ]
