# Generated by Django 4.0.6 on 2022-08-09 03:42

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_maktab_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='kollejbitiruvchisi',
            name='univer_sity',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name="Topshirmoqchi bo'lgan universitet"),
        ),
        migrations.AddField(
            model_name='maktabbitiruvchisi',
            name='sinf',
            field=models.CharField(choices=[('9-sinf', '9-sinf'), ('11-sinf', '11-sinf')], default='9-sinf', max_length=300, verbose_name='Sinf'),
        ),
        migrations.AddField(
            model_name='maktabbitiruvchisi',
            name='univer_sity',
            field=models.CharField(default=django.utils.timezone.now, max_length=300, verbose_name="Topshirmoqchi bo'lgan universitet"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='universitetbitiruvchisi',
            name='universitet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.universitet', verbose_name='Bitirayotgan OTM'),
        ),
    ]
