# Generated by Django 4.0.6 on 2022-08-16 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_bitiruvchi_email_alter_bitiruvchi_t_sana'),
    ]

    operations = [
        migrations.AddField(
            model_name='kollejbitiruvchisi',
            name='kollej',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.kollej', verbose_name='Bitirayotgan Kollej'),
        ),
    ]
