# Generated by Django 4.0.6 on 2022-08-16 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_kollejbitiruvchisi_kollej'),
    ]

    operations = [
        migrations.AddField(
            model_name='kollejbitiruvchisi',
            name='kolleJ',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Bitirayotgan kollej'),
        ),
        migrations.AddField(
            model_name='universitetbitiruvchisi',
            name='universiteT',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Bitirayotgan OTM'),
        ),
        migrations.AlterField(
            model_name='bitiruvchi',
            name='t_sana',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name="Tug'ulgan sana"),
        ),
    ]
