# Generated by Django 4.0.6 on 2022-08-17 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_kollejbitiruvchisi_kollej_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kollejbitiruvchisi',
            name='stu_way',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Mutaxasislik'),
        ),
        migrations.AddField(
            model_name='universitetbitiruvchisi',
            name='stu_way',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Mutaxasislik'),
        ),
    ]
