# Generated by Django 4.0.6 on 2022-08-17 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_bitiruvchi_t_sana'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverLicense',
            fields=[
                ('autotime_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.autotime')),
            ],
            bases=('main.autotime',),
        ),
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('autotime_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.autotime')),
            ],
            bases=('main.autotime',),
        ),
        migrations.RemoveField(
            model_name='bitiruvchi',
            name='guvohnoma',
        ),
        migrations.AddField(
            model_name='bitiruvchi',
            name='uy',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name="Ko'cha nomi 45uy"),
        ),
        migrations.AddField(
            model_name='maktabbitiruvchisi',
            name='tuman_mk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.tumanvashahar', verbose_name='Maktab manzili'),
        ),
        migrations.AlterField(
            model_name='bitiruvchi',
            name='img',
            field=models.ImageField(default='default/default.png', upload_to='bitiruvchilar-foto/', verbose_name='Rasm'),
        ),
        migrations.AlterField(
            model_name='bitiruvchi',
            name='imkonyat',
            field=models.ManyToManyField(related_name='abilty', to='main.imkonyat', verbose_name='Kompyuter bilimi'),
        ),
        migrations.AlterField(
            model_name='bitiruvchi',
            name='phone',
            field=models.CharField(blank=True, max_length=9, null=True, verbose_name='Telefon raqam (+998) '),
        ),
        migrations.AddField(
            model_name='bitiruvchi',
            name='sport',
            field=models.ManyToManyField(blank=True, null=True, related_name='sport', to='main.sport', verbose_name='Qiziqadigan sport turi'),
        ),
        migrations.AddField(
            model_name='kollejbitiruvchisi',
            name='guvohnoma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.driverlicense', verbose_name='Haydovchilik Guvohnomasi'),
        ),
        migrations.AddField(
            model_name='universitetbitiruvchisi',
            name='guvohnoma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.driverlicense', verbose_name='Haydovchilik Guvohnomasi'),
        ),
    ]
