# Generated by Django 4.0.6 on 2022-08-17 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_driverlicense_sport_remove_bitiruvchi_guvohnoma_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bitiruvchi',
            name='sport',
            field=models.ManyToManyField(related_name='sport', to='main.sport', verbose_name='Qiziqadigan sport turi'),
        ),
    ]
