# Generated by Django 4.0.6 on 2022-08-18 04:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_bitiruvchi_sport'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeKollej',
            fields=[
                ('autotime_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.autotime')),
            ],
            bases=('main.autotime',),
        ),
        migrations.AddField(
            model_name='kollejbitiruvchisi',
            name='tuman_kj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.tumanvashahar', verbose_name='Kollej manzili'),
        ),
        migrations.AlterField(
            model_name='bitiruvchi',
            name='idea',
            field=models.CharField(choices=[('Bor', 'Bor'), ('Yoq', 'Yoq')], default='Yoq', max_length=300, verbose_name="Biznes g'oya"),
        ),
        migrations.AddField(
            model_name='kollejbitiruvchisi',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.typekollej', verbose_name="Professional ta'lim"),
        ),
    ]
