# Generated by Django 4.0.6 on 2022-08-18 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_kollej_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kollej',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.typekollej', verbose_name="Ta'lim muassasasi turi"),
        ),
    ]
