# Generated by Django 4.0.6 on 2022-08-21 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_kollej_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='universitet',
            name='tuman',
        ),
        migrations.AddField(
            model_name='maktabbitiruvchisi',
            name='otm_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.universitet', verbose_name="Topshirmoqchi bo'lgan OTM Nomi"),
        ),
        migrations.AddField(
            model_name='maktabbitiruvchisi',
            name='stu_way_un',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Mutaxasislik'),
        ),
        migrations.AddField(
            model_name='maktabbitiruvchisi',
            name='tuman_un',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tuman_mk_un', to='main.tumanvashahar', verbose_name='OTM manzili'),
        ),
    ]
