# Generated by Django 4.0.6 on 2022-08-21 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_remove_universitet_tuman_maktabbitiruvchisi_otm_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maktabbitiruvchisi',
            name='other_un',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Boshqa OTM nomi'),
        ),
    ]
