# Generated by Django 4.0.6 on 2022-08-21 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_maktabbitiruvchisi_other_un'),
    ]

    operations = [
        migrations.AddField(
            model_name='kollejbitiruvchisi',
            name='other_un',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='bishqa otm'),
        ),
        migrations.AddField(
            model_name='kollejbitiruvchisi',
            name='otm_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.universitet'),
        ),
        migrations.AddField(
            model_name='kollejbitiruvchisi',
            name='stu_way_un',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Mutaxasislik'),
        ),
        migrations.AddField(
            model_name='kollejbitiruvchisi',
            name='tuman_un',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tuman_kj_un', to='main.tumanvashahar'),
        ),
    ]
