# Generated by Django 4.0.6 on 2022-08-21 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_kollejbitiruvchisi_other_un_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='universitetbitiruvchisi',
            name='tuman_un',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.tumanvashahar'),
        ),
    ]
