# Generated by Django 4.0.6 on 2022-08-21 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_universitetbitiruvchisi_tuman_un'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vil',
            fields=[
                ('autotime_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.autotime')),
            ],
            bases=('main.autotime',),
        ),
        migrations.RemoveField(
            model_name='kollejbitiruvchisi',
            name='tuman_un',
        ),
        migrations.RemoveField(
            model_name='maktabbitiruvchisi',
            name='tuman_un',
        ),
        migrations.RemoveField(
            model_name='universitetbitiruvchisi',
            name='tuman_un',
        ),
        migrations.AddField(
            model_name='universitetbitiruvchisi',
            name='other_un',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='kollejbitiruvchisi',
            name='vil',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kj_vil', to='main.vil'),
        ),
        migrations.AddField(
            model_name='maktabbitiruvchisi',
            name='vil',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mk_vil', to='main.vil', verbose_name='OTM manzili'),
        ),
        migrations.AddField(
            model_name='universitet',
            name='viloyat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.vil', verbose_name='viloyat nomi'),
        ),
        migrations.AddField(
            model_name='universitetbitiruvchisi',
            name='vil',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.vil'),
        ),
    ]
