# Generated by Django 4.0.6 on 2022-08-22 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_vil_remove_kollejbitiruvchisi_tuman_un_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bitiruvchi',
            name='millat',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
