# Generated by Django 4.0.6 on 2022-08-22 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_bitiruvchi_millat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maktab',
            name='status',
            field=models.CharField(blank=True, choices=[("O'rta ta'lim maktabi", "O'rta ta'lim maktabi"), ("O'rta ta'lim maktabi", "O'rta ta'lim maktabi")], default="O'rta ta'lim maktabi", max_length=300, null=True),
        ),
    ]
