# Generated by Django 4.0.6 on 2022-08-22 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_alter_maktab_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='maktabbitiruvchisi',
            name='maqsad',
            field=models.CharField(blank=True, choices=[("O'qishni davom etirmoqchi", "O'qishni davom etirmoqchi"), ('Ishlamoqchi', 'Ishlamoqchi')], default='Ishlamoqchi', max_length=300, null=True, verbose_name='Maqsadi'),
        ),
    ]
