# Generated by Django 4.0.6 on 2022-08-22 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_maktabbitiruvchisi_maqsad'),
    ]

    operations = [
        migrations.AddField(
            model_name='kollejbitiruvchisi',
            name='stu_way_ch',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Mutaxasislik'),
        ),
        migrations.AddField(
            model_name='maktabbitiruvchisi',
            name='stu_way_ch',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Mutaxasislik'),
        ),
        migrations.AddField(
            model_name='universitetbitiruvchisi',
            name='stu_way_ch',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Mutaxasislik'),
        ),
        migrations.AlterField(
            model_name='kollejbitiruvchisi',
            name='other_un',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='chetel otm'),
        ),
        migrations.AlterField(
            model_name='maktabbitiruvchisi',
            name='other_un',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='ChetEl OTM nomi'),
        ),
        migrations.AlterField(
            model_name='universitetbitiruvchisi',
            name='other_un',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='ChetEl OTM'),
        ),
    ]
