# Generated by Django 4.0.6 on 2022-08-23 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_kollejbitiruvchisi_stu_way_ch_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maktab',
            name='status',
            field=models.CharField(blank=True, choices=[("O'rta ta'lim maktabi", "O'rta ta'lim maktabi"), ('Ixtisoslashgan maktablar', 'Ixtisoslashgan maktablar')], default="O'rta ta'lim maktabi", max_length=300, null=True),
        ),
    ]
