# Generated by Django 4.0.6 on 2022-08-24 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_alter_maktab_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kollejbitiruvchisi',
            name='guvohnoma',
        ),
        migrations.AddField(
            model_name='kollejbitiruvchisi',
            name='guvohnoma',
            field=models.ManyToManyField(blank=True, null=True, related_name='guvohnomaK', to='main.driverlicense', verbose_name='Haydovchilik Guvohnomasi'),
        ),
        migrations.RemoveField(
            model_name='universitetbitiruvchisi',
            name='guvohnoma',
        ),
        migrations.AddField(
            model_name='universitetbitiruvchisi',
            name='guvohnoma',
            field=models.ManyToManyField(blank=True, null=True, related_name='guvohnomaU', to='main.driverlicense', verbose_name='Haydovchilik Guvohnomasi'),
        ),
    ]
