# Generated by Django 4.0.6 on 2022-08-24 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_remove_kollejbitiruvchisi_guvohnoma_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kollejbitiruvchisi',
            name='guvohnoma',
            field=models.ManyToManyField(related_name='guvohnomaK', to='main.driverlicense', verbose_name='Haydovchilik Guvohnomasi'),
        ),
        migrations.AlterField(
            model_name='universitetbitiruvchisi',
            name='guvohnoma',
            field=models.ManyToManyField(related_name='guvohnomaU', to='main.driverlicense', verbose_name='Haydovchilik Guvohnomasi'),
        ),
    ]
